name: isar
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  isar_flutter_libs: ^1.0.0+1
  path_provider: ^2.1.4
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.12
  lints: ^3.0.0
  test: ^1.24.0
